### ISSUE TITLE
ENV

### ISSUE THREAD

**Issue by Inthreal** [FilipToth/SocialCredit#5]
Is there a option to make the variables in config.ts into env variables, instead of using the config.json inside SRC?

**Comment by FilipToth** [comment]
There currently is not, but this would be a nice thing to add. I'd actually prefer using a `.env` than the current setup. I can drop a PR if you'd like.

**Comment by Inthreal** [comment]
sure, thanks!

**Comment by FilipToth** [comment]
Hi! I've switched the entire config system to use dotenv in PR #6.

**Comment by Inthreal** [comment]
YOO TYY!

**Comment by FilipToth** [comment]
Ok, I'm closing this issue for now, since the ENV system has been implemented.
